<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_footer_robot</name>
   <tag></tag>
   <elementGuidId>e93a7324-345b-4ed6-8800-998dfea5c648</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.footer_robot</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page_wrapper']/footer/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c4698c79-fa07-4488-90cc-1e2246877747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Swag Bot Footer</value>
      <webElementGuid>bb1e37bb-8d1c-401b-aa24-ea2894336881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>footer_robot</value>
      <webElementGuid>1636caed-bf23-4e7c-8e93-b88dec92b4be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/SwagBot_Footer_graphic.2e87acec.png</value>
      <webElementGuid>3b17a732-b9e7-44b6-8623-a9ebc9f47c01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page_wrapper&quot;)/footer[@class=&quot;footer&quot;]/img[@class=&quot;footer_robot&quot;]</value>
      <webElementGuid>ae917ec0-7f0f-4c8f-be44-2ecb2f915999</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page_wrapper']/footer/img</value>
      <webElementGuid>02801cdc-9282-49fb-bf66-ce435321f1bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Swag Bot Footer']</value>
      <webElementGuid>b461db1e-5ed0-49e8-b63c-aa4faec6bfb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/img</value>
      <webElementGuid>a2e42b93-fc7c-4077-8a3a-40d1931b1c39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Swag Bot Footer' and @src = '/static/media/SwagBot_Footer_graphic.2e87acec.png']</value>
      <webElementGuid>df2d3580-875c-467e-bf45-774c6a43980a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
